development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://batecbsaxitnwx:950ff9f96ade9ded0a0b7f17c5f5548744a27c8df17c25d88887bf8191c2633c@ec2-23-23-101-25.compute-1.amazonaws.com:5432/d34g41r5dfatnt
  channel_prefix: railsappnew_production
